"use client";
import Link from "next/link";
import { Search } from "lucide-react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { PurchasesPagination } from "@/components/purchases/purchases-pagination";
import { useBusiness } from "@/contexts/business-context";
import { useDocuments } from "@/features/documents/hooks/use-documents";
import { businessDocumentStatus, bytes, documentStatuses, documentTypes, page, size, status, title, type } from "@/features/documents/utils/document-utils";
import { DocumentBadge } from "./document-badge";
import { DocumentEmpty, DocumentError, DocumentLoading } from "./document-states";

export function DocumentList() {
  const { activeBusinessId } = useBusiness(); const params = useSearchParams(); const router = useRouter(); const pathname = usePathname();
  const query = { page: page(params.get("page")), pageSize: size(params.get("page_size")), documentType: type(params.get("type")), status: status(params.get("status")) };
  const result = useDocuments(activeBusinessId ?? "", query);
  const setFilter = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); next.set("page", "1"); router.push(`${pathname}?${next}`); };
  return <div className="space-y-4"><div><h2 className="text-lg font-semibold">Document queue</h2><p className="text-sm text-muted-foreground">Filter by the document type or reading status supported by the backend.</p></div><div className="grid gap-3 rounded-xl border bg-muted/20 p-4 lg:grid-cols-[1.3fr_1fr_1fr]"><label className="text-xs text-muted-foreground">Search documents<div className="relative mt-1"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2" aria-hidden="true" /><input disabled aria-describedby="document-search-help" placeholder="Search is not available" className="h-10 w-full rounded-md border bg-muted pl-9 pr-3 text-sm disabled:cursor-not-allowed disabled:opacity-70" /></div><span id="document-search-help" className="mt-1 block">The backend does not currently support document search.</span></label><Select label="Document type" value={query.documentType ?? ""} set={value => setFilter("type", value)}><option value="">All types</option>{documentTypes.map(item => <option key={item} value={item}>{title(item)}</option>)}</Select><Select label="Reading status" value={query.status ?? ""} set={value => setFilter("status", value)}><option value="">All statuses</option>{documentStatuses.map(item => <option key={item} value={item}>{businessDocumentStatus(item)}</option>)}</Select></div>{result.isLoading ? <DocumentLoading /> : result.isError ? <DocumentError retry={() => void result.refetch()} /> : !result.data?.data.length ? <DocumentEmpty title="No documents found" description="No documents match the selected backend filters." /> : <><div className="overflow-hidden rounded-xl border">{result.data.data.map(document => <Link key={document.id} href={`/documents/${document.id}`} className="grid gap-2 border-b p-4 transition-colors last:border-0 hover:bg-muted/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring md:grid-cols-[2fr_1fr_1fr_1fr_auto] md:items-center"><strong className="truncate">{document.original_filename}<small className="block font-normal text-muted-foreground">{bytes(document.file_size)} · {document.page_count} {document.page_count === 1 ? "page" : "pages"}</small></strong><span>{title(document.document_type)}</span><span>{new Date(document.uploaded_at).toLocaleDateString()}</span><DocumentBadge value={businessDocumentStatus(document.status)} tone={document.status === "ocr_completed" ? "good" : document.status === "ocr_failed" ? "bad" : "neutral"} /><span className="sr-only">Open document</span><span aria-hidden="true">→</span></Link>)}</div><PurchasesPagination page={result.data.meta.page} pages={result.data.meta.pages} pageSize={result.data.meta.size} /></>}</div>;
}
function Select({ label, value, set, children }: { label: string; value: string; set: (value: string) => void; children: React.ReactNode }) { return <label className="text-xs text-muted-foreground">{label}<select className="mt-1 h-10 w-full rounded-md border bg-background px-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring" value={value} onChange={event => set(event.target.value)}>{children}</select></label>; }
