"use client";
import Link from "next/link";
import { Archive, Pencil, RotateCcw } from "lucide-react";
import { toast } from "sonner";
import { BusinessEntityInformationCard, BusinessEntityUnavailableCard } from "@/components/entities/business-entity-cards";
import { EntityStatusBadge } from "@/components/entities/entity-workspace";
import { Button } from "@/components/ui/button";
import { useBusiness } from "@/contexts/business-context";
import { useCatalogItem, useCatalogMutations } from "@/features/catalog/hooks/use-catalog";
import { CatalogError, CatalogLoading } from "./catalog-states";

const value=(input:string|number|null)=>input===null?null:String(input); const money=(input:string|number)=>new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(Number(input));
export function CatalogDetail({id}:{id:string}){const{activeBusinessId}=useBusiness(),item=useCatalogItem(activeBusinessId??"",id),mutations=useCatalogMutations();if(item.isLoading)return <CatalogLoading label="Loading item"/>;if(item.isError||!item.data)return <CatalogError retry={()=>void item.refetch()}/>;if(item.data.business_id!==activeBusinessId)return <section role="alert" className="rounded-xl border p-6">This item does not belong to the active business.</section>;const data=item.data,archived=data.status==="archived";const change=async()=>{try{await mutations.setArchived.mutateAsync({businessId:activeBusinessId,id,archived:!archived});toast.success(archived?"Item restored":"Item archived")}catch(error){toast.error(error instanceof Error?error.message:"Status could not be changed")}};return <div className="space-y-6"><header className="flex flex-col gap-4 rounded-xl border p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-semibold">{data.name}</h2><EntityStatusBadge active={!archived}/></div><p className="mt-1 text-sm capitalize text-muted-foreground">{data.item_type}{data.code?` · ${data.code}`:""}</p></div><div className="flex flex-wrap gap-2"><Button asChild variant="outline"><Link href={`/catalog/${id}/edit`}><Pencil/>Edit</Link></Button><Button variant="outline" disabled={mutations.setArchived.isPending} onClick={()=>void change()}>{archived?<RotateCcw/>:<Archive/>}{archived?"Restore":"Archive"}</Button></div></header><div className="grid gap-4 lg:grid-cols-2"><BusinessEntityInformationCard title="Basic information" description="Canonical commercial identity" fields={[["Name",data.name],["Type",data.item_type],["Code / SKU",data.code],["Default unit",data.default_unit],["Category",data.category],["Barcode",data.barcode]]}/><BusinessEntityInformationCard title="Pricing" description="Backend-stored commercial values" fields={[["Selling price",money(data.selling_price)],["Purchase price",money(data.purchase_price)]]}/><BusinessEntityInformationCard title="GST classification" description="Reusable tax classification" fields={[[data.item_type==="product"?"HSN":"SAC",data.hsn_code||data.sac_code],["GST rate",`${value(data.gst_rate)}%`],["Cess rate",`${value(data.cess_rate)}%`]]}/><BusinessEntityInformationCard title="Description" description="Shared item description" fields={[["Description",data.description]]}/><BusinessEntityUnavailableCard title="Inventory information" description="Inventory is an optional catalog capability. No canonical inventory-profile API is available yet, so stock data is not inferred from legacy product endpoints."/><BusinessEntityUnavailableCard title="Usage history" description="Usage history is unavailable because the backend does not expose catalog-item relationships or activity history."/></div></div>}
