"use client";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useBusiness } from "@/contexts/business-context";
import { EntityStatusBadge } from "@/components/entities/entity-workspace";
import { PurchasesPagination } from "@/components/purchases/purchases-pagination";
import { useCatalogItems } from "@/features/catalog/hooks/use-catalog";
import type { CatalogStatus, ItemType } from "@/features/catalog/types/catalog.types";
import { CatalogEmpty, CatalogError, CatalogLoading } from "./catalog-states";

const page=(value:string|null)=>Math.max(1,Number(value)||1); const size=(value:string|null)=>[10,20,50,100].includes(Number(value))?Number(value):20;
export function CatalogList(){const {activeBusinessId}=useBusiness(),params=useSearchParams(),router=useRouter(),pathname=usePathname();const itemType=(params.get("item_type")||undefined) as ItemType|undefined,status=(params.get("status")||undefined) as CatalogStatus|undefined;const query={page:page(params.get("page")),pageSize:size(params.get("page_size")),itemType,status};const result=useCatalogItems(activeBusinessId??"",query);const set=(key:string,value:string)=>{const next=new URLSearchParams(params);if(value)next.set(key,value);else next.delete(key);next.set("page","1");router.push(`${pathname}?${next}`)};return <section className="space-y-4"><div className="grid gap-3 rounded-xl border bg-muted/20 p-4 sm:grid-cols-2"><Filter label="Item type" value={itemType??""} onChange={v=>set("item_type",v)}><option value="">Products and services</option><option value="product">Products</option><option value="service">Services</option></Filter><Filter label="Status" value={status??""} onChange={v=>set("status",v)}><option value="">All statuses</option><option value="active">Active</option><option value="archived">Archived</option></Filter><p className="text-xs text-muted-foreground sm:col-span-2">Search, category filters, and sorting are unavailable because the catalog API does not expose them.</p></div>{result.isLoading?<CatalogLoading/>:result.isError?<CatalogError retry={()=>void result.refetch()}/>:!result.data?.data.length?<CatalogEmpty filtered={Boolean(itemType||status)}/>:<><div className="overflow-hidden rounded-xl border"><div className="hidden grid-cols-[2fr_1fr_1fr_1fr_1fr_auto] gap-3 border-b bg-muted/40 px-4 py-3 text-xs uppercase text-muted-foreground md:grid"><span>Item</span><span>Type</span><span>Code</span><span>Tax code</span><span>Unit</span><span>Status</span></div>{result.data.data.map(item=><Link key={item.id} href={`/catalog/${item.id}`} className="grid gap-2 border-b p-4 transition-colors last:border-0 hover:bg-muted/30 md:grid-cols-[2fr_1fr_1fr_1fr_1fr_auto] md:items-center"><span className="font-medium">{item.name}<small className="block font-normal text-muted-foreground">{item.category||"No category"}</small></span><span className="capitalize">{item.item_type}</span><span className="font-mono text-sm">{item.code||"—"}</span><span>{item.hsn_code||item.sac_code||"—"}</span><span>{item.default_unit}</span><EntityStatusBadge active={item.status==="active"}/></Link>)}</div><PurchasesPagination page={result.data.meta.page} pages={result.data.meta.pages} pageSize={result.data.meta.size}/></>}</section>}
function Filter({label,value,onChange,children}:{label:string;value:string;onChange:(value:string)=>void;children:React.ReactNode}){return <label className="text-xs font-medium text-muted-foreground">{label}<select className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm" value={value} onChange={event=>onChange(event.target.value)}>{children}</select></label>}
