"""Conversation-scoped assistant workflow tracking."""

from dataclasses import dataclass
from datetime import datetime

from app.common.models.abstract.timestamp import utc_now
from app.modules.assistant.context.schemas import ContextProvenance
from app.modules.assistant.memory.policies import WORKFLOW_TTL_HOURS, expires_in_hours
from app.modules.assistant.models import (
    AssistantWorkflow,
    AssistantWorkflowStatus,
    AssistantWorkflowType,
    ContextSource,
)

WORKFLOW_KEYWORDS: dict[AssistantWorkflowType, tuple[str, ...]] = {
    AssistantWorkflowType.SALES_INVOICE: ("sales invoice", "invoice", "customer"),
    AssistantWorkflowType.PURCHASE_INVOICE: ("purchase", "supplier"),
    AssistantWorkflowType.EXPENSE_REVIEW: ("expense", "vendor", "receipt"),
    AssistantWorkflowType.GST_REVIEW: ("gst", "gstr", "filing"),
    AssistantWorkflowType.INVENTORY_CHECK: ("inventory", "stock", "warehouse"),
    AssistantWorkflowType.DOCUMENT_REVIEW: ("document", "ocr", "extract"),
    AssistantWorkflowType.ACCOUNTING_REPORT: (
        "trial balance",
        "balance sheet",
        "profit and loss",
    ),
}


@dataclass(frozen=True)
class WorkflowTransition:
    """Typed workflow transition generated by deterministic rules."""

    workflow_type: AssistantWorkflowType
    status: AssistantWorkflowStatus
    current_step: str
    active_entity_refs: list[dict[str, object]]
    pending_decisions: list[dict[str, object]]
    provenance: dict[str, object]
    expires_at: datetime


class WorkflowTracker:
    """Infer and transition assistant workflow state without executing business work."""

    def infer_workflow_type(self, message: str) -> AssistantWorkflowType:
        """Infer workflow type from deterministic keywords."""
        normalized = message.lower()
        for workflow_type, keywords in WORKFLOW_KEYWORDS.items():
            if any(keyword in normalized for keyword in keywords):
                return workflow_type
        return AssistantWorkflowType.GENERAL

    def infer_status(self, message: str) -> AssistantWorkflowStatus:
        """Infer workflow state from the current user message."""
        normalized = message.lower()
        if any(term in normalized for term in ("confirm", "approve", "save")):
            return AssistantWorkflowStatus.READY_FOR_ACTION
        asks_question = "?" in message or any(
            term in normalized for term in ("which", "what", "how")
        )
        if asks_question:
            return AssistantWorkflowStatus.WAITING_FOR_USER
        return AssistantWorkflowStatus.ACTIVE

    def build_transition(
        self,
        *,
        message: str,
        active_entity_refs: list[dict[str, object]],
    ) -> WorkflowTransition:
        """Build a deterministic workflow transition payload."""
        workflow_type = self.infer_workflow_type(message)
        status = self.infer_status(message)
        provenance = ContextProvenance(
            source=ContextSource.USER_MESSAGE.value,
            source_id=None,
            source_version="assistant-workflow-rules-v1",
            generated_by="WorkflowTracker",
            generated_at=utc_now(),
        )
        pending_decisions: list[dict[str, object]] = []
        if status == AssistantWorkflowStatus.WAITING_FOR_USER:
            pending_decisions.append(
                {
                    "decision": "clarify_user_intent",
                    "reason": "User message requires a follow-up answer or decision.",
                }
            )
        return WorkflowTransition(
            workflow_type=workflow_type,
            status=status,
            current_step=self._step_for(workflow_type, status),
            active_entity_refs=active_entity_refs,
            pending_decisions=pending_decisions,
            provenance=provenance.model_dump(mode="json"),
            expires_at=expires_in_hours(WORKFLOW_TTL_HOURS),
        )

    def workflow_context_payload(
        self,
        workflow: AssistantWorkflow,
    ) -> dict[str, object]:
        """Return workflow state in prompt-context shape."""
        return {
            "workflow_type": workflow.workflow_type.value,
            "status": workflow.status.value,
            "current_step": workflow.current_step,
            "active_entity_refs": workflow.active_entity_refs,
            "pending_decisions": workflow.pending_decisions,
            "expires_at": workflow.expires_at.isoformat(),
            "provenance": workflow.provenance,
        }

    def _step_for(
        self,
        workflow_type: AssistantWorkflowType,
        status: AssistantWorkflowStatus,
    ) -> str:
        """Return a human-readable assistant workflow step."""
        if workflow_type == AssistantWorkflowType.GENERAL:
            return "understand_user_request"
        if status == AssistantWorkflowStatus.READY_FOR_ACTION:
            return "waiting_for_explicit_confirmation"
        if status == AssistantWorkflowStatus.WAITING_FOR_USER:
            return "waiting_for_user_decision"
        return f"assist_{workflow_type.value}"
