import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import type { Customer } from "@/features/sales/types/sales.types";

export function CustomerInformationCard({ customer }: { customer: Customer }) { return <InfoCard title="Customer information" description="Identity used across sales records" items={[["Customer code", customer.customer_code], ["Status", customer.is_active ? "Active" : "Archived"]]} />; }
export function ContactInformationCard({ customer }: { customer: Customer }) { return <InfoCard title="Contact information" description="Ways to contact this customer" items={[["Email", customer.email], ["Phone", customer.phone]]} />; }
export function GSTInformationCard({ customer }: { customer: Customer }) { return <InfoCard title="GST information" description="Verified fields stored on the customer record" items={[["GSTIN", customer.gstin], ["PAN", customer.pan]]} />; }
export function AddressCard({ customer }: { customer: Customer }) { return <InfoCard title="Addresses" description="Billing and shipping details" items={[["Billing address", customer.billing_address], ["Shipping address", customer.shipping_address]]} />; }
export function CustomerActivityCard() { return <Card><CardHeader><CardTitle>Customer activity</CardTitle><CardDescription>Relationship history across TaxPilot</CardDescription></CardHeader><CardContent><p className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">Last activity, payments, outstanding balances, and GST history are not available from the current customer API.</p></CardContent></Card>; }
function InfoCard({ title, description, items }: { title: string; description: string; items: [string, string | null][] }) { return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent><dl className="space-y-4">{items.map(([label, value]) => <div key={label}><dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 whitespace-pre-wrap text-sm">{value || "Unavailable"}</dd></div>)}</dl></CardContent></Card>; }
