"use client";
import Link from "next/link";
import { Plus } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { useBusiness } from "@/contexts/business-context";
import { useCustomerNames, useInvoices } from "@/features/sales/hooks/use-sales";
import { formatDate, formatMoney, parsePage, parsePageSize } from "@/features/sales/utils/sales-format";
import { InvoiceStatusBadge } from "./sales-badges";
import { SalesEmpty, SalesError, SalesLoading, UnsupportedTools } from "./sales-states";
import { SalesPagination } from "./sales-pagination";
export function InvoiceList(){const{activeBusinessId}=useBusiness(),params=useSearchParams(),page=parsePage(params.get("page")),pageSize=parsePageSize(params.get("page_size")),query=useInvoices(activeBusinessId??"",page,pageSize),names=useCustomerNames(query.data?.data.map(item=>item.customer_id)??[]);if(query.isLoading)return <SalesLoading/>;if(query.isError||!query.data)return <SalesError retry={()=>void query.refetch()}/>;const data=query.data;return <div className="space-y-4"><header className="flex flex-col items-start justify-between gap-3 sm:flex-row sm:items-end"><div><h2 className="text-xl font-semibold">Canonical invoices</h2><p className="text-sm text-muted-foreground">Draft, issue, and cancellation workflow backed by the canonical Sales API.</p></div><Button asChild><Link href="/sales/invoices/new"><Plus/>New invoice</Link></Button></header><UnsupportedTools/>{data.data.length===0?<SalesEmpty title="No canonical invoices" description="Create a draft invoice using a customer and canonical catalog items."/>:<><div className="overflow-hidden rounded-xl border"><div className="hidden grid-cols-[1fr_1.2fr_1fr_1fr_auto] gap-4 border-b bg-muted/40 px-4 py-3 text-xs uppercase text-muted-foreground md:grid"><span>Invoice</span><span>Customer</span><span>Date</span><span>Total</span><span>Status</span></div>{data.data.map(invoice=><Link key={invoice.id} href={`/sales/invoices/${invoice.id}`} className="grid gap-2 border-b p-4 last:border-0 hover:bg-muted/40 md:grid-cols-[1fr_1.2fr_1fr_1fr_auto] md:items-center"><p className="font-medium">{invoice.invoice_number}</p><p className="text-sm">{names.get(invoice.customer_id)??invoice.customer_id}</p><div className="text-sm"><p>{formatDate(invoice.invoice_date)}</p><p className="text-xs text-muted-foreground">Due {formatDate(invoice.due_date)}</p></div><p className="font-medium tabular-nums">{formatMoney(invoice.total_amount)}</p><InvoiceStatusBadge status={invoice.status}/></Link>)}</div><SalesPagination page={data.meta.page} pages={data.meta.pages} pageSize={data.meta.size}/></>}</div>}
