import { afterAll, afterEach, beforeAll, describe, expect, it } from "vitest"; import { http, HttpResponse } from "msw"; import { server } from "@/test/mocks/server"; import { purchasesApi } from "./purchases-api";
const base = "http://localhost:8000/api/v1"; beforeAll(() => server.listen({ onUnhandledRequest: "error" })); afterEach(() => server.resetHandlers()); afterAll(() => server.close());
describe("purchases API integration", () => {
  it("sends only verified purchase-list filters", async () => { server.use(http.get(`${base}/purchases`, ({ request }) => { expect([...new URL(request.url).searchParams.entries()]).toEqual([["business_id","b1"],["page","2"],["page_size","20"],["sort","-invoice_date"],["supplier","s1"],["status","approved"],["invoice_date_from","2026-01-01"]]); return HttpResponse.json({ success: true, message: "ok", data: [], meta: { page: 2, size: 20, total: 0, pages: 0 } }); })); await purchasesApi.invoices("b1", { page: 2, pageSize: 20, sort: "-invoice_date", supplier: "s1", status: "approved", invoiceDateFrom: "2026-01-01" }); });
  it("does not combine search with ignored filters or sort", async () => { server.use(http.get(`${base}/purchases`, ({ request }) => { expect([...new URL(request.url).searchParams.keys()]).toEqual(["business_id","page","page_size","search"]); return HttpResponse.json({ success: true, message: "ok", data: [], meta: { page: 1, size: 20, total: 0, pages: 0 } }); })); await purchasesApi.invoices("b1", { page: 1, pageSize: 20, search: "INV", sort: "due_date", status: "paid" }); });
  it("uses verified lifecycle path without an invented body", async () => { server.use(http.post(`${base}/purchases/p1/approve`, async ({ request }) => { expect(await request.text()).toBe(""); return HttpResponse.json({ success: true, message: "ok", data: { id: "p1", status: "approved" } }); })); await expect(purchasesApi.transition("p1", "approve")).resolves.toMatchObject({ status: "approved" }); });
  it("uses verified supplier create and archive contracts", async () => { const input = { name: "Aarav Wholesale", email: null, phone: null, gstin: null, pan: null, address: null, payment_terms: null, is_active: true }; server.use(http.post(`${base}/purchases/suppliers`, async ({ request }) => { expect(new URL(request.url).searchParams.get("business_id")).toBe("b1"); expect(await request.json()).toEqual(input); return HttpResponse.json({ success: true, message: "ok", data: { id: "s1", business_id: "b1", supplier_code: "SUP-1", ...input } }); }), http.delete(`${base}/purchases/suppliers/s1`, () => new HttpResponse(null, { status: 204 }))); await expect(purchasesApi.createSupplier("b1", input)).resolves.toMatchObject({ id: "s1" }); await expect(purchasesApi.deactivateSupplier("s1")).resolves.toBeUndefined(); });
  it("uses the verified supplier restore endpoint", async () => { server.use(http.post(`${base}/purchases/suppliers/s1/reactivate`, () => HttpResponse.json({ success: true, message: "ok", data: { id: "s1", is_active: true } }))); await expect(purchasesApi.reactivateSupplier("s1")).resolves.toMatchObject({ is_active: true }); });
});
